# Generated by Django 2.1.3 on 2018-11-19 06:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacultyName', models.TextField()),
                ('Designation', models.TextField()),
                ('EmailId', models.TextField()),
                ('Mobile', models.TextField()),
                ('Date_Entry', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
