# Generated by Django 2.1.3 on 2018-11-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='FacultyName',
            field=models.CharField(max_length=150),
        ),
    ]
