# Generated by Django 2.1.3 on 2018-11-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181119_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='Designation',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='EmailId',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='Mobile',
            field=models.CharField(max_length=150),
        ),
    ]
